# backend/Dockerfile.sandbox
FROM node:22-alpine

# Установим необходимые языки
RUN apk add --no-cache \
    python3 \
    g++ \
    openjdk17-jdk \
    && rm -rf /var/cache/apk/*

# Убедимся, что python3 доступен как python
RUN ln -sf python3 /usr/bin/python

# Установим node_modules
WORKDIR /app
COPY package*.json ./
RUN npm install

# Скопируем исходный код
COPY . .

# Убедимся, что у нас есть папка для временных файлов
RUN mkdir -p /app/temp

# Установим пользователя
USER node

EXPOSE 3001

CMD ["npm", "run", "start"]