export interface VocabTerm {
  id: number;
  term: string;
  transcription: string;
  translation: string;
  category: string;
  definition: string;
  example: string;
  level: 'basic' | 'intermediate' | 'advanced';
}

export const CATEGORIES = [
  'Программирование',
  'Сети',
  'IoT / Железо',
  'Безопасность',
  'Базы данных',
  'ИИ / ML',
  'Общее',
];

export const VOCAB: VocabTerm[] = [
  // ── Программирование ────────────────────────────────────────────
  { id: 1,  term: 'Algorithm',       transcription: '[ˈælɡərɪðəm]',     translation: 'Алгоритм',           category: 'Программирование', level: 'basic',        definition: 'A step-by-step procedure for solving a problem or accomplishing a task.',                               example: 'The sorting algorithm runs in O(n log n) time.' },
  { id: 2,  term: 'Compiler',        transcription: '[kəmˈpaɪlər]',      translation: 'Компилятор',         category: 'Программирование', level: 'basic',        definition: 'A program that translates source code into machine code.',                                             example: 'The compiler reported three syntax errors in the code.' },
  { id: 3,  term: 'Debugging',       transcription: '[diːˈbʌɡɪŋ]',       translation: 'Отладка',            category: 'Программирование', level: 'basic',        definition: 'The process of finding and fixing errors (bugs) in software.',                                          example: 'She spent hours debugging the authentication module.' },
  { id: 4,  term: 'Refactoring',     transcription: '[riːˈfæktərɪŋ]',    translation: 'Рефакторинг',        category: 'Программирование', level: 'intermediate', definition: 'Restructuring existing code without changing its external behavior.',                                   example: 'Refactoring improved code readability significantly.' },
  { id: 5,  term: 'Recursion',       transcription: '[rɪˈkɜːʃən]',       translation: 'Рекурсия',           category: 'Программирование', level: 'intermediate', definition: 'A function that calls itself to solve a smaller version of the same problem.',                          example: 'The factorial function is a classic example of recursion.' },
  { id: 6,  term: 'Abstraction',     transcription: '[æbˈstrækʃən]',     translation: 'Абстракция',         category: 'Программирование', level: 'intermediate', definition: 'Hiding complexity by exposing only essential features.',                                                example: 'The API provides abstraction over the database layer.' },
  { id: 7,  term: 'Polymorphism',    transcription: '[ˌpɒlɪˈmɔːfɪzəm]',  translation: 'Полиморфизм',        category: 'Программирование', level: 'advanced',     definition: 'The ability of different objects to respond to the same interface in different ways.',                  example: 'Polymorphism allows the same draw() call to render different shapes.' },
  { id: 8,  term: 'Encapsulation',   transcription: '[ɪnˌkæpsʊˈleɪʃən]',translation: 'Инкапсуляция',       category: 'Программирование', level: 'advanced',     definition: 'Bundling data and methods that operate on that data within a single unit.',                           example: 'Encapsulation protects internal state from external modification.' },
  { id: 9,  term: 'Dependency',      transcription: '[dɪˈpendənsi]',     translation: 'Зависимость',        category: 'Программирование', level: 'basic',        definition: 'A module or library that another module relies on.',                                                   example: 'Install all dependencies by running npm install.' },
  { id: 10, term: 'Middleware',      transcription: '[ˈmɪdəlweər]',      translation: 'Промежуточное ПО',   category: 'Программирование', level: 'intermediate', definition: 'Software that connects different systems or handles requests before they reach the main handler.',      example: 'The authentication middleware checks tokens on every request.' },

  // ── Сети ────────────────────────────────────────────────────────
  { id: 11, term: 'Bandwidth',       transcription: '[ˈbændwɪdθ]',       translation: 'Пропускная способность', category: 'Сети', level: 'basic',        definition: 'The maximum rate of data transfer across a network.',                                                  example: 'The server upgrade doubled our available bandwidth.' },
  { id: 12, term: 'Latency',         transcription: '[ˈleɪtənsi]',       translation: 'Задержка',           category: 'Сети',             level: 'basic',        definition: 'The time delay between sending and receiving data.',                                                   example: 'High latency causes lag in real-time applications.' },
  { id: 13, term: 'Protocol',        transcription: '[ˈprəʊtəkɒl]',      translation: 'Протокол',           category: 'Сети',             level: 'basic',        definition: 'A set of rules governing communication between network devices.',                                       example: 'HTTP is the protocol used for web communication.' },
  { id: 14, term: 'Packet',          transcription: '[ˈpækɪt]',          translation: 'Пакет',              category: 'Сети',             level: 'basic',        definition: 'A unit of data transmitted over a network.',                                                           example: 'Each packet contains a header with routing information.' },
  { id: 15, term: 'Throughput',      transcription: '[ˈθruːpʊt]',        translation: 'Пропускная способность (факт.)', category: 'Сети', level: 'intermediate', definition: 'The actual amount of data successfully delivered per unit of time.',                              example: 'Network congestion reduced throughput to 50% of capacity.' },
  { id: 16, term: 'Handshake',       transcription: '[ˈhændʃeɪk]',       translation: 'Квитирование',       category: 'Сети',             level: 'intermediate', definition: 'The process where two systems establish connection parameters before transferring data.',             example: 'TLS uses a three-way handshake to establish a secure session.' },
  { id: 17, term: 'Gateway',         transcription: '[ˈɡeɪtweɪ]',        translation: 'Шлюз',               category: 'Сети',             level: 'basic',        definition: 'A network node that connects two different networks.',                                                 example: 'The default gateway routes traffic to the internet.' },
  { id: 18, term: 'Subnet',          transcription: '[ˈsʌbnet]',         translation: 'Подсеть',            category: 'Сети',             level: 'intermediate', definition: 'A logical subdivision of an IP network.',                                                              example: 'Devices on the same subnet can communicate directly.' },

  // ── IoT / Железо ────────────────────────────────────────────────
  { id: 19, term: 'Firmware',        transcription: '[ˈfɜːmweər]',       translation: 'Прошивка',           category: 'IoT / Железо',     level: 'basic',        definition: 'Low-level software permanently programmed into hardware.',                                             example: 'Update the firmware to fix the connectivity bug.' },
  { id: 20, term: 'Microcontroller', transcription: '[ˌmaɪkrəʊkənˈtrəʊlər]', translation: 'Микроконтроллер', category: 'IoT / Железо',  level: 'basic',        definition: 'A compact integrated circuit with a processor, memory, and I/O peripherals.',                       example: 'The ESP32 microcontroller includes built-in Wi-Fi.' },
  { id: 21, term: 'GPIO',            transcription: '[ˌdʒiːpiːaɪˈəʊ]',  translation: 'Цифровой порт ввода/вывода', category: 'IoT / Железо', level: 'basic',  definition: 'General Purpose Input/Output — configurable digital pins on a microcontroller.',                    example: 'Set GPIO pin 2 as output to control the LED.' },
  { id: 22, term: 'Polling',         transcription: '[ˈpəʊlɪŋ]',         translation: 'Опрос',              category: 'IoT / Железо',     level: 'intermediate', definition: 'Repeatedly checking the status of an input or device.',                                                example: 'Polling the sensor every 100 ms consumes unnecessary power.' },
  { id: 23, term: 'Interrupt',       transcription: '[ˈɪntərʌpt]',       translation: 'Прерывание',         category: 'IoT / Железо',     level: 'intermediate', definition: 'A signal that pauses normal program execution to handle an event.',                                   example: 'Configure an interrupt to trigger when the button is pressed.' },
  { id: 24, term: 'PWM',             transcription: '[ˌpiːdʌbljuːˈem]',  translation: 'Широтно-импульсная модуляция', category: 'IoT / Железо', level: 'intermediate', definition: 'Pulse Width Modulation — controlling power by varying the duty cycle of a signal.',     example: 'Use PWM to control motor speed without voltage regulation.' },
  { id: 25, term: 'I2C',             transcription: '[ˌaɪ tuː ˈsiː]',    translation: 'Протокол I2C',       category: 'IoT / Железо',     level: 'intermediate', definition: 'Inter-Integrated Circuit — a two-wire serial communication protocol.',                               example: 'Connect the OLED display using I2C on pins SDA and SCL.' },
  { id: 26, term: 'SPI',             transcription: '[ˌespiːˈaɪ]',       translation: 'Протокол SPI',       category: 'IoT / Железо',     level: 'intermediate', definition: 'Serial Peripheral Interface — a four-wire synchronous communication bus.',                           example: 'The SD card module communicates via SPI.' },
  { id: 27, term: 'ADC',             transcription: '[ˌeɪdiːˈsiː]',      translation: 'АЦП',                category: 'IoT / Железо',     level: 'basic',        definition: 'Analog-to-Digital Converter — converts analog signals to digital values.',                           example: 'The ADC reads sensor voltage as a 12-bit integer.' },

  // ── Безопасность ────────────────────────────────────────────────
  { id: 28, term: 'Authentication',  transcription: '[ɔːˌθentɪˈkeɪʃən]', translation: 'Аутентификация',    category: 'Безопасность',     level: 'basic',        definition: 'Verifying the identity of a user or system.',                                                         example: 'Two-factor authentication adds an extra security layer.' },
  { id: 29, term: 'Encryption',      transcription: '[ɪnˈkrɪpʃən]',      translation: 'Шифрование',         category: 'Безопасность',     level: 'basic',        definition: 'The process of encoding data so only authorized parties can read it.',                               example: 'All passwords must be stored with encryption.' },
  { id: 30, term: 'Vulnerability',   transcription: '[ˌvʌlnərəˈbɪlɪti]', translation: 'Уязвимость',        category: 'Безопасность',     level: 'intermediate', definition: 'A weakness in a system that can be exploited by attackers.',                                          example: 'The security audit discovered a SQL injection vulnerability.' },
  { id: 31, term: 'Payload',         transcription: '[ˈpeɪləʊd]',        translation: 'Полезная нагрузка',  category: 'Безопасность',     level: 'intermediate', definition: 'The part of transmitted data that is the actual message or malicious content.',                      example: 'The malware payload activates 24 hours after infection.' },
  { id: 32, term: 'Token',           transcription: '[ˈtəʊkən]',         translation: 'Токен',              category: 'Безопасность',     level: 'basic',        definition: 'A digital key used to verify identity or authorize access.',                                          example: 'The JWT token expires after one hour.' },

  // ── Базы данных ─────────────────────────────────────────────────
  { id: 33, term: 'Query',           transcription: '[ˈkwɪəri]',         translation: 'Запрос',             category: 'Базы данных',       level: 'basic',        definition: 'A request for data from a database.',                                                                 example: 'The SQL query returned 500 records in under a second.' },
  { id: 34, term: 'Index',           transcription: '[ˈɪndeks]',         translation: 'Индекс',             category: 'Базы данных',       level: 'intermediate', definition: 'A data structure that improves the speed of data retrieval.',                                         example: 'Adding an index on the email column sped up login queries.' },
  { id: 35, term: 'Transaction',     transcription: '[trænˈzækʃən]',     translation: 'Транзакция',         category: 'Базы данных',       level: 'intermediate', definition: 'A sequence of operations treated as a single unit that must fully succeed or fail.',                 example: 'The payment transaction rolled back due to insufficient funds.' },
  { id: 36, term: 'Migration',       transcription: '[maɪˈɡreɪʃən]',     translation: 'Миграция',           category: 'Базы данных',       level: 'intermediate', definition: 'The process of moving or transforming database schema or data.',                                     example: 'The migration script added three new columns to the users table.' },
  { id: 37, term: 'Schema',          transcription: '[ˈskiːmə]',         translation: 'Схема',              category: 'Базы данных',       level: 'basic',        definition: 'The structure that defines the organization of data in a database.',                                 example: 'The database schema was redesigned to support multi-tenancy.' },

  // ── ИИ / ML ─────────────────────────────────────────────────────
  { id: 38, term: 'Training',        transcription: '[ˈtreɪnɪŋ]',        translation: 'Обучение (модели)',   category: 'ИИ / ML',           level: 'basic',        definition: 'The process of feeding data to a model so it can learn patterns.',                                  example: 'Training the model on larger datasets improved accuracy.' },
  { id: 39, term: 'Inference',       transcription: '[ˈɪnfərəns]',       translation: 'Вывод (предсказание)',category: 'ИИ / ML',           level: 'intermediate', definition: 'Using a trained model to make predictions on new data.',                                            example: 'Inference on edge devices requires optimized models.' },
  { id: 40, term: 'Overfitting',     transcription: '[ˌəʊvəˈfɪtɪŋ]',    translation: 'Переобучение',       category: 'ИИ / ML',           level: 'intermediate', definition: 'When a model learns training data too well, failing to generalize.',                                  example: 'Dropout layers help prevent overfitting in neural networks.' },
  { id: 41, term: 'Epoch',           transcription: '[ˈiːpɒk]',          translation: 'Эпоха',              category: 'ИИ / ML',           level: 'basic',        definition: 'One complete pass through the entire training dataset.',                                              example: 'After 50 epochs, the loss converged to 0.02.' },
  { id: 42, term: 'Feature',         transcription: '[ˈfiːtʃər]',        translation: 'Признак',            category: 'ИИ / ML',           level: 'basic',        definition: 'An individual measurable property used as input to a model.',                                       example: 'Temperature and humidity are features for weather prediction.' },

  // ── Общее ────────────────────────────────────────────────────────
  { id: 43, term: 'Deploy',          transcription: '[dɪˈplɔɪ]',         translation: 'Развёртывать',       category: 'Общее',             level: 'basic',        definition: 'To release software to a production environment.',                                                    example: 'We deploy to production every Friday afternoon.' },
  { id: 44, term: 'Scalability',     transcription: '[ˌskeɪləˈbɪlɪti]',  translation: 'Масштабируемость',   category: 'Общее',             level: 'intermediate', definition: 'The ability of a system to handle increased load.',                                                    example: 'Microservices improve the scalability of large applications.' },
  { id: 45, term: 'Throughput',      transcription: '[ˈθruːpʊt]',        translation: 'Производительность', category: 'Общее',             level: 'intermediate', definition: 'The number of tasks or transactions a system processes per unit time.',                              example: 'After optimization, throughput increased by 40%.' },
  { id: 46, term: 'Bottleneck',      transcription: '[ˈbɒtəlnek]',       translation: 'Узкое место',        category: 'Общее',             level: 'basic',        definition: 'A point in a system that limits overall performance.',                                                example: 'The database was identified as the main bottleneck.' },
  { id: 47, term: 'Legacy',          transcription: '[ˈleɡəsi]',         translation: 'Устаревший (о коде)',category: 'Общее',             level: 'basic',        definition: 'Outdated software or systems that are still in use.',                                                 example: 'The legacy codebase made adding new features difficult.' },
  { id: 48, term: 'Deprecate',       transcription: '[ˈdeprɪkeɪt]',      translation: 'Объявлять устаревшим', category: 'Общее',           level: 'intermediate', definition: 'To mark a feature as outdated and discourage its use.',                                              example: 'This API endpoint will be deprecated in version 3.0.' },
  { id: 49, term: 'Boilerplate',     transcription: '[ˈbɔɪlərpleɪt]',    translation: 'Шаблонный код',      category: 'Общее',             level: 'intermediate', definition: 'Repetitive code sections that appear in many places with little change.',                           example: 'The framework reduces boilerplate in API controllers.' },
  { id: 50, term: 'Benchmark',       transcription: '[ˈbentʃmɑːk]',      translation: 'Тест производительности', category: 'Общее',        level: 'basic',        definition: 'A test used to measure the performance of a system.',                                                 example: 'Run the benchmark suite before and after the optimization.' },
];
